# RINT Data Manager Configuration

server:
  host: "0.0.0.0"
  port: 7123
  debug: true
  reload: true

database:
  url: "sqlite:///rint_data_manager.db"
  echo: false

dvc:
  storage_path: "/opt/dvc_storage"
  remote_name: "local_storage"
  uploads_dvc_project: "/opt/dvc_storage/uploads"

upload:
  directory: "/opt/dvc_storage/uploads"
  max_file_size: 104857600  # 100MB in bytes
  allowed_extensions: [".csv", ".json", ".txt", ".xlsx", ".parquet", ".h5", ".pkl", ".py", ".ipynb"]

auth:
   jwt_secret_key: "your-secret-key-here-change-in-production"
   jwt_algorithm: "HS256"
   jwt_expiration_minutes: 1440  # 24 hours
   password_min_length: 8
   email_suffix_regex: ".*@hillstonenet\\.com$|.*@Hillstonenet\\.com$"

cors:
  allowed_origins: ["http://localhost:7123", "http://127.0.0.1:7123", "http://10.160.43.82:7123"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "app.log"
