# RINT Data Manager Configuration
# All values can be overridden with environment variables using the pattern:
# RINT_SECTION_KEY (e.g., RINT_SERVER_PORT, RINT_DATABASE_URL)

server:
  host: "0.0.0.0"
  port: 8000
  debug: true
  reload: true

database:
  url: "sqlite:///rint_data_manager.db"
  echo: false

dvc:
  # Common storage configuration
  storage_path: "/cyberange/data/dvc-storage"

  # Internal DVC operations (existing functionality)
  remote_name: "local_storage"
  uploads_dvc_project: "/tmp/rdm/uploads"

  # Upload configuration
  upload_directory: "/tmp/rdm/uploads"
  max_file_size: 104857600  # 100MB in bytes
  allowed_extensions: [".csv", ".json", ".txt", ".xlsx", ".parquet", ".h5", ".pkl", ".py", ".ipynb"]

  # HTTP remote server (new functionality)
  remote_server:
    enabled: false
    auth:
      enabled: true  # when "false", the DVC HTTP server accept all pushed data anonymously
      method: "database"  # database, basic, custom, none
      database_auth:
        require_admin: false  # Whether only admin users can access DVC remote
        allowed_users: []  # Empty list means all registered users can access
      basic_auth:
        username: "dvc_user"
        password: "dvc_password"
      custom_auth:
        header_name: "X-DVC-Token"
        token: "your-custom-token-here"
    ssl_verify: true
    read_timeout: 300
    connect_timeout: 300

auth:
   jwt_secret_key: "your-secret-key-here-change-in-production"
   jwt_algorithm: "HS256"
   jwt_expiration_minutes: 1440  # 24 hours
   password_min_length: 8
   email_suffix_regex: ".*@hillstonenet\\.com$|.*@Hillstonenet\\.com$"

cors:
  allowed_origins: ["http://localhost:8000", "http://127.0.0.1:8000"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "log/app.log"

timing_debug:
  enabled: false
  log_level: "INFO"
  include_frontend: false
  detailed_logging: false
